name: bitapp_functional_dart
description: A minimal functional library written entirely in dart.
version: 1.0.4
# homepage: https://www.example.com
repository: https://github.com/openbitapp/functional-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  #pedantic: ^1.9.0
  test: ^1.14.4
